### ISSUE TITLE
New box renderer

### ISSUE THREAD

**Issue by amitdo** [amitdo/tesseract#3]
https://github.com/amitdo/tesseract/commit/8fe2d918e447

**Comment by amitdo** [comment]
I didn't test yet if Tesseract accept this box file and works well with it.

@Shreeshrii
You are invited to test it if you want.

**Comment by amitdo** [comment]
The command - something like this:
`tesseract image.tiff output -l lang --oem 1 makelinesbox`

**Comment by amitdo** [comment]
should be tested with varoius images and languages. 
eng, hin, ara (RTL) ...

**Comment by Shreeshrii** [comment]
Please let me know the git command to use to apply this patch. 

I usually use `git pull origin`  to get changes from tesseract repo.

**Comment by Shreeshrii** [comment]
git remote add amit https://github.com/amitdo/tesseract.git
git pull amit -b make-lines-boxes

**Comment by Shreeshrii** [comment]
Making all in configs
make[3]: Entering directory `/mnt/c/Users/User/shree/tesseract-ocr/tessdata/configs'
make[3]: *** No rule to make target `makelinesbox', needed by `all-am'.  Stop.
make[3]: Leaving directory `/mnt/c/Users/User/shree/tesseract-ocr/tessdata/configs'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/mnt/c/Users/User/shree/tesseract-ocr/tessdata'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/c/Users/User/shree/tesseract-ocr'
make: *** [all] Error 2
sudo: unable to resolve host ALL-IN-1-TOUCH

**Comment by amitdo** [comment]
I suggest to start with the most simple lang - eng.

It is possible that hin and ara will suffer from unrelated bugs which you already reported.


If ara doesn't work well, you can try heb, which is also a rtl lang.

**Comment by Shreeshrii** [comment]
it did not build, got error. Probably missing config file ...

**Comment by Shreeshrii** [comment]
there is also - https://github.com/amitdo/tesseract/blob/master/tessdata/configs/linebox

i haven't tested that either.

**Comment by amitdo** [comment]
I will check again the code.
 
I think this config file is used to convert from lines box file to regular chars box file.

**Comment by amitdo** [comment]
I can build the code with no error reported.

**Comment by Shreeshrii** [comment]
do u have a config file named `makelinesbox` - it is not there in repo
https://github.com/amitdo/tesseract/tree/master/tessdata/configs

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
Oops...


I have it, but for some reason it is not present in the repo. I will push a new commit.
Thanks.

**Comment by amitdo** [comment]
Fixed in https://github.com/amitdo/tesseract/commit/673bbd1da464b1fe68ebf8bc1e1840036083245b

**Comment by amitdo** [comment]
`tesseract image.tiff output -l lang --oem 1 makelinesbox`

BTW, It also works with png files.
`tesseract image.png output -l lang --oem 1 makelinesbox`

**Comment by Shreeshrii** [comment]
is --oem 1 required? I want to try and test with the files for deu_frak,
that traineddata is for 3.0x.

ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by amitdo** [comment]
Not required, just recommended. If the traineddata file does not have lstm support use '--oem 0'.

**Comment by amitdo** [comment]
Imported note: The text after '#; need to be verified and corrected if necessary.
Keep the spaces between glyphs.

This will make your testing more hard.

**Comment by amitdo** [comment]
Take your time, no hurry...

**Comment by amitdo** [comment]
For rtl the textlines strings are reversed and should be kept reversed. This will make it hard to people to correct the text.

**Comment by Shreeshrii** [comment]
The box file is adding a space after each character. See one sample file for deu_frak .

Added .txt extenstion to upload.
[deu_frak.embedsiver.exp0makelinesbox.box.txt](https://github.com/amitdo/tesseract/files/721034/deu_frak.embedsiver.exp0makelinesbox.box.txt)

This is the corrected file - based on the original box file.
[deu_frak.embedsiver.exp0.box.txt](https://github.com/amitdo/tesseract/files/721035/deu_frak.embedsiver.exp0.box.txt)

**Comment by Shreeshrii** [comment]
Here are couple of samples of one devanagari image, processed using -l san and -l hin.

[san001-san.box.txt](https://github.com/amitdo/tesseract/files/721038/san001-san.box.txt)
[san001-hin.box.txt](https://github.com/amitdo/tesseract/files/721039/san001-hin.box.txt)

**Comment by amitdo** [comment]
The spaces are required.

**Comment by Shreeshrii** [comment]
In that case it will be very difficult for a user to create these box files. I thought that Ray said that it would be easy as # needed to be followed by the line text.

>In this format the boxes only need to cover a textline instead of individual characters.

>WordStr <left> <bottom> <right> <top> <page> #<text for line including spaces>

>'WordStr' is a literal string that directs the box file parser to take the actual text string from the end of the line after the '#' character.

**Comment by amitdo** [comment]
In some langs, some 'symbols' will be written with more than one char.

**Comment by amitdo** [comment]
>In that case it will be very difficult for a user to create these box files. I thought that Ray said that it would be easy as # needed to be followed by the line text.

You are right.
We need new 3rd party tools to help with editing this box format.

**Comment by Shreeshrii** [comment]
>It should be possible, using sed or some other such utility for modifying text files in a batch mode to take those original box files and add lines for boxes with tabs - whenever the horizontal positioning changes for each line.

@stweil this is for the existing deu_frak box/tiff pairs. Wondering whether it is possible to add the boxes with tabs programmatically.

**Comment by Shreeshrii** [comment]
For testing, I modified the box file by using jtessboxeditor, by adding a new box at end of each line.

**Comment by Shreeshrii** [comment]
The spaces are required.

Amit,

 I think these box files should be created with the normal line text. There
needs to be an additional step within tesseract, which splits the line as
required either by characters/symbols/aksharas etc, as required for the
language.

This processing is probably already being done in text2image.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/amitdo/tesseract/issues/3#issuecomment-274250308>, or mute
the thread

**Comment by amitdo** [comment]
Yes, it can be done.

I can easily do the first part - output the string without spaces, like in your corrected files.

I do not know how hard it will be to implement the other parts with **C++**.

**Comment by amitdo** [comment]
> It should be possible, using sed or some other such utility for modifying text files in a batch mode to take those original box files and add lines for boxes with tabs - whenever the horizontal positioning changes for each line.

Where this quote comes from.

>@stweil this is for the existing deu_frak box/tiff pairs. Wondering whether it is possible to add the boxes with tabs programmatically.

This seems to be the easiest approach.

**Comment by Shreeshrii** [comment]
quote is from one of my earlier posts. I included @stweil in the
conversation, since he had mentioned about deu_frak with 4.0.



ShreeDevi
____________________________________________________________
भजन - कीर्तन - आरती @ http://bhajans.ramparivar.com

**Comment by Shreeshrii** [comment]
@amitdo Please see https://github.com/tesseract-ocr/tesseract/issues/670

The full text line option with normal text seems to be giving error. Probably needs to be as you generated .

**Comment by Shreeshrii** [comment]
That version is also giving an error:

```
=== Phase UP: Generating unicharset and unichar properties files ===
[Sat Jan 21 19:13:19 DST 2017] /usr/local/bin/unicharset_extractor -D /tmp/tmp.h9bu6erqqa/frk/ /tmp/tmp.h9bu6erqqa/frk/frk.embedsiver.exp0.box /tmp/tmp.h9bu6erqqa/frk/
frk.embedsiverline.exp0.box /tmp/tmp.h9bu6erqqa/frk/frk.UnifrakturMaguntia.exp0.box /tmp/tmp.h9bu6erqqa/frk/frk.Walbaum-Fraktur.exp0.box
Utf8 buffer too big, size=31 for E m i l i e , h a n s K o n e .
Utf8 buffer too big, size=35 for Y i r ch , C a n c e ll i r a a d .
Utf8 buffer too big, size=37 for s t a u t - a - h a n s D a t t e r .
Utf8 buffer too big, size=43 for O t t o R o s e n , F u l d m c e g t i g .
Utf8 buffer too big, size=46 for c A n d e r s - , T j e n e r h o c B i r ch .
Utf8 buffer too big, size=35 for G n T j e n e t h o s M ø ll e r .
Utf8 buffer too big, size=98 for H a n d l i n g e n f o r e g a a e r i K i ø b e n h a v n , i S l u t n i n g e n a f 1 8 4 8 .
Extracting unicharset from /tmp/tmp.h9bu6erqqa/frk/frk.embedsiver.exp0.box
Extracting unicharset from /tmp/tmp.h9bu6erqqa/frk/frk.embedsiverline.exp0.box
Extracting unicharset from /tmp/tmp.h9bu6erqqa/frk/frk.UnifrakturMaguntia.exp0.box
Extracting unicharset from /tmp/tmp.h9bu6erqqa/frk/frk.Walbaum-Fraktur.exp0.box
Wrote unicharset file /tmp/tmp.h9bu6erqqa/frk//unicharset.
[Sat Jan 21 19:13:19 DST 2017] /usr/local/bin/set_unicharset_properties -U /tmp/tmp.h9bu6erqqa/frk/frk.unicharset -O /tmp/tmp.h9bu6erqqa/frk/frk.unicharset -X /tmp/tmp
.h9bu6erqqa/frk/frk.xheights --script_dir=../langdata
Loaded unicharset of size 46 from file /tmp/tmp.h9bu6erqqa/frk/frk.unicharset
Setting unichar properties
```

**Comment by amitdo** [comment]
My format is the right format.

`unicharset_extractor` need some more code to read it right.

**Comment by Shreeshrii** [comment]
Yes, it is the right format. You also pointed out the comments in
https://github.com/tesseract-ocr/tesseract/blob/master/ccmain/applybox.cpp

```
* In the word/line-level form, the line begins with the literal "WordStr", and
 * the bounding box bounds either a whole line or a whole word. The recognizable
 * units in the word/line are listed after the # at the end of the line and
 * are space delimited, ignoring any original spaces on the line.
 * Eg.
 * @verbatim
 * word -> #w o r d
 * multi word line -> #m u l t i w o r d l i n e
 * @endverbatim
 * The recognizable units must be space-delimited in order to allow multiple
 * unicodes to be used for a single recognizable unit, eg Hindi.

```

For Hindi, the recognizable units will have multiple unicodes. So it might be akshara based

```
WordStr 1302 4300 1893 4425 0 #वि ष या नु क्र म णि का
WordStr 436 4098 1819 4223 0 #ज्वा ला मु खी स ह स्र ना म स्तो त्र म् - ना मा ब लि :
WordStr 422 3896 1646 4029 0 #दु र्गा  स ह स्र ना म स्तो त्र म् - १ ना मा ब लि :
WordStr 422 3698 1630 3825 0 #दु र्गा  स ह स्र ना म स्तो त्र म् - २ ना मा व लि :
```

instead of

```
WordStr 1302 4300 1893 4425 0 #वि ष या नु क् र म णि का
WordStr 436 4098 1819 4223 0 #ज् वा ला मु खी स ह स् र ना म स् तो त् र म् - ना मा ब लि :
WordStr 422 3896 1646 4029 0 #दु र्गा स ह स् र ना म स् तो त् र म् - १ ना मा ब लि :
WordStr 422 3698 1630 3825 0 #दु र्गा स ह स् र ना म स् तो त् र म् - २ ना मा व लि :
```

So, the recognizable strings have to as in the unicharset.
Here is a sample from a sample unicharset in devanagari script:

```
482
NULL 0 NULL 0
Joined 7 0,69,188,255,486,1218,0,30,486,1188 Latin 1 0 1 Joined	# Joined [4a 6f 69 6e 65 64 ]a
|Broken|0|1 f 0,69,186,255,892,2138,0,80,892,2058 Common 2 10 2 |Broken|0|1	# Broken
अ 1 64,64,192,193,121,174,0,12,132,167 Devanagari 3 0 3 अ	# अ [905 ]x
नु 1 0,64,67,197,106,127,0,0,106,127 Devanagari 81 0 81 नु	# नु [928 941 ]x
वा 1 62,65,192,197,143,188,0,0,143,188 Devanagari 17 0 17 वा	# वा [935 93e ]x
द 1 34,72,192,192,100,122,0,0,99,114 Devanagari 6 0 6 द	# द [926 ]x
क 1 63,64,192,192,145,166,0,0,144,154 Devanagari 7 0 7 क	# क [915 ]x
र्ता 1 3,65,61,197,234,302,0,0,234,302 Devanagari 21 0 21 र्ता	# र्ता [930 94d 924 93e ]x
प्र 1 3,64,61,197,178,230,0,0,178,230 Devanagari 26 0 26 प्र	# प्र [92a 94d 930 ]x
का 1 62,65,192,197,187,219,0,0,187,219 Devanagari 7 0 7 का	# का [915 93e ]x
श 1 61,64,192,195,128,148,0,12,130,147 Devanagari 11 0 11 श	# श [936 ]x
ना 1 62,65,192,197,149,191,0,0,149,191 Devanagari 81 0 81 ना	# ना [928 93e ]x
रि 1 58,65,192,253,121,175,0,0,121,175 Devanagari 21 0 21 रि	# रि [930 93f ]x
तां 1 61,76,192,242,153,268,0,0,153,268 Devanagari 30 0 30 तां	# तां [924 93e 902 ]x
गु 1 0,64,67,197,99,134,0,0,99,134 Devanagari 68 0 68 गु	# गु [917 941 ]x
रु 1 0,64,67,197,81,111,0,0,81,111 Devanagari 21 0 21 रु	# रु [930 941 ]x
व 1 63,64,192,192,101,128,0,0,100,123 Devanagari 17 0 17 व	# व [935 ]x
र्य 1 3,64,61,197,192,244,0,0,192,244 Devanagari 21 0 21 र्य	# र्य [930 94d 92f ]x
प्रे 1 3,76,61,255,178,349,0,0,178,349 Devanagari 26 0 26 प्रे	# प्रे [92a 94d 930 947 ]x
मा 1 62,65,192,197,149,198,0,0,149,198 Devanagari 39 0 39 मा	# मा [92e 93e ]x
र 1 58,64,192,192,84,119,0,0,81,110 Devanagari 21 0 21 र	# र [930 ]x
पू 1 1,64,67,197,97,120,0,0,97,120 Devanagari 26 0 26 पू	# पू [92a 942 ]x
र्व 1 3,64,61,197,181,234,0,0,181,234 Devanagari 21 0 21 र्व	# र्व [930 94d 935 ]x
```

**Comment by Shreeshrii** [comment]
See Ray's comment at https://github.com/tesseract-ocr/tesseract/issues/654#issuecomment-274192153

**Comment by amitdo** [comment]
Hindi:
Does the second example (after 'instead of...') is what you get with `makelinesbox`
Does the regular box file produced by  `tesseract .... makebox`) is written correctly?

**Comment by Shreeshrii** [comment]
Yes, the 2nd one is from new box renderer.

Yes, old makbox splits them as per unicharset , see

https://github.com/Shreeshrii/imagessan/blob/master/san95-box-tiff/san.AA_NAGARI_SHREE_L2.exp0.box

for a sample.

There maybe an issue if the training text has a grapheme that was not in
the original unicharset.

With LSTM training, the unicharset is not saved separately.

- excuse the brevity, sent from mobile

On 24-Jan-2017 8:07 PM, "Amit D." <notifications@github.com> wrote:

Hindi:
Does the second example (after 'instead of...') is what you get with
makelinesbox
Does the regular box file produced by tesseract .... makebox) is written
correctly?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/amitdo/tesseract/issues/3#issuecomment-274820336>, or mute
the thread

**Comment by amitdo** [comment]
>Yes, old makbox splits them as per unicharset , see

with `--oem 0`? What about `--oem 1`?

**Comment by Shreeshrii** [comment]
Will try tomorrow and let you know.

- excuse the brevity, sent from mobile

**Comment by amitdo** [comment]
Thanks. Please also check `makelinesbox` with `--oem 0` instead of `-oem 1`.

**Comment by amitdo** [comment]
>Please also check `makelinesbox` with `--oem 0` instead of `-oem 1`.

for Hindi.

**Comment by Shreeshrii** [comment]
OK. Here are the files from testing.

I will post first the image used and the corresponding ground truth file.

![san001](https://cloud.githubusercontent.com/assets/5095331/22286598/b891e788-e315-11e6-9bca-2d5d237040e9.png)
[san001-gt.txt](https://github.com/amitdo/tesseract/files/729221/san001-gt.txt)

**Comment by Shreeshrii** [comment]
This box file is created by text2image program, as part of the tesstrain.sh rendering process for the above groundtruth file used as training text with Siddhanta font. Also attaching the generated image - the page number column is not separated since it was not that way in ground truth.

The original image above is in a different unknown font with colummnar formatting.

However, I wanted to include this case, since this is the format that is CURRENTLY BEING USED by LSTM training.

[hin.Siddhanta.exp0.box.txt](https://github.com/amitdo/tesseract/files/729238/hin.Siddhanta.exp0.box.txt)
![hin siddhanta exp0](https://cloud.githubusercontent.com/assets/5095331/22286844/8013441e-e316-11e6-86be-ef90aeb7f8ba.png)

**Comment by Shreeshrii** [comment]
From what  I can make out in the above,

comjuncts involving ra are combined eg. kra, tra, rgaa, rva. As also nna, ShTa etc. 
Other half letters are in separate boxes. 

This could be dependent on the font/pango.

**Comment by Shreeshrii** [comment]
Here are the box files with makebox, with --oem 0 and --oem 1. Please note that OCR accuracy is lower with --oem 0 for Hindi.

[san001-hin-makebox-1.box.txt](https://github.com/amitdo/tesseract/files/729270/san001-hin-makebox-1.box.txt)
[san001-hin-makebox-0.box.txt](https://github.com/amitdo/tesseract/files/729271/san001-hin-makebox-0.box.txt)

**Comment by Shreeshrii** [comment]
Here are the box files with new box renderer with --oem 0 and --oem 1. The splitting of glyphs seems to match makebox but not text2image.

[san001-hin-makelinesbox-1.box.txt](https://github.com/amitdo/tesseract/files/729280/san001-hin-makelinesbox-1.box.txt)
[san001-hin-makelinesbox-0.box.txt](https://github.com/amitdo/tesseract/files/729281/san001-hin-makelinesbox-0.box.txt)

**Comment by Shreeshrii** [comment]
What I would like to suggest is this.

Given an image and its ground truth file with the normal (non space delimited) text, tesseract or some other utility program, create the box file in the WordStr format.

However, instead of using tesseract to OCR the page (which is not 100% accurate) to get the characters string (similar to makebox), you use the corresponding line of text from the groundtruth file and process it similar to text2image to get the splitup string for the box file.

This will have the benefit of being easier for the users, they only have to provide normal text.

In cases, where users do not have the ground truth file to begin with, the image can be OCRed to create a draft groundtruth file which can be corrected by the user.

The corrected ground truth with the image can be used for generating the line box file.

**Comment by Shreeshrii** [comment]
The boxes created with makelinesbox will most probably work just fine. I am not able to test any further because the current code does not support this format fully.

My suggestion is mainly for ease of users creating/correcting box files.

Thanks!

**Comment by amitdo** [comment]
Thanks Shree. I will **try** to see if I can improve the code. Probably next week.

**Comment by Shreeshrii** [comment]
FYI:  Quan has implemented adding EOL with Tab character to existing box files in Jtessboxeditor - 

Version 2.0 Beta (31 January 2017)
- Upgrade Tesseract training executable 4.0dev (2017-01-30)
- Implement Add EOL with Tab character

![mark-eol](https://cloud.githubusercontent.com/assets/5095331/23575747/79dbeb36-00b8-11e7-910a-8818482ff7cf.png)

**Comment by amitdo** [comment]
Thanks for the info.

I prefer to wait to the next big round of changes before submitting a patch for 4.00.
I have no clue when it will come.

**Comment by amitdo** [comment]
I'm sorry, I don't know how to make the needed changes in Tesseract for supporting the WordStr format.
